### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by g4c3** [zjunlp/Mol-Instructions#10]
Hi there. I have some problem with the requirements. After configuring and activating conda env
1st I ran: 
pip install torch==1.12.0+cu116 torchvision==0.13.0+cu116 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu116
Then:
pip install -r requirements.txt
Ended up with:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
peft 0.3.0 requires torch>=1.13.0, but you have torch 1.12.0+cu116 which is incompatible.

How can I setup the env correctrly? 

Thanks in advance and Merry Christmas

**Comment by Fangyinfff** [comment]
Hi,

It seems like there's a version conflict with the torch package in your environment.
The code we have provided is compatible with `peft 0.2.0`. To install `peft 0.3.0`, you're correct in needing to install the following versions:
```
pip install torch==1.13.0+cu117 torchvision==0.14.0+cu117 torchaudio==0.13.0+cu117 --extra-index-url https://download.pytorch.org/whl/cu117
```

Merry Christmas to you too!
