### ISSUE TITLE
Regarding some questions about the paper.

### ISSUE THREAD

**Issue by tfwang08** [zjunlp/Mol-Instructions#11]
Hi, I'm reading your paper and have a question about Figure 5. Can you share the specific numerical values in that figure or guide me to where I can find them? Thanks!

**Comment by Fangyinfff** [comment]
Hi, the specific numerical values you are looking for are provided in the following chart. Please refer to this for the detailed information you need.

<img width="640" alt="image" src="https://github.com/zjunlp/Mol-Instructions/assets/61076726/06b0ac34-1ba5-41be-bd7a-a0a9ee878a30">

I hope this helps!

**Comment by tfwang08** [comment]
Thank you very much for your response. Is the 'LLama' in the table referring to llama 1?

**Comment by Fangyinfff** [comment]
It refers to LLama-2-chat.
