### ISSUE TITLE
can not find config.json

### ISSUE THREAD

**Issue by chengfengke** [zjunlp/Mol-Instructions#12]
<img width="613" alt="截屏2024-03-18 15 06 59" src="https://github.com/zjunlp/Mol-Instructions/assets/56249816/25a4f468-4b67-4aaa-b204-c1000248b8d9">

**Comment by Fangyinfff** [comment]
Hello, I'm not sure which code you were running when you encountered the error. It might be due to an incorrect path. Based on the screenshot, it appears to involve the `config.json` file.

**Comment by zxlzr** [comment]
Do you have any further questions?

**Comment by chengfengke** [comment]
ah,I've got a new question,I would like to know, where can I get the llama foundation model, I run it, but when it load the llama, it would throw that error, which is ValueError: Converting into mixed 8-bit weights from tf/flax weights is currently not supported, please make sure the weights are in 
PyTorch format. I got my llama-2-7b-hf on the model scope,does it fit your model?
<img width="520" alt="image" src="https://github.com/zjunlp/Mol-Instructions/assets/56249816/9b7e4eed-4bb9-4786-bb03-85bcdffdbb3c">

**Comment by chengfengke** [comment]
if you don't mind, may you add my WeChat and give us some recommendation? +86 13021115937

**Comment by Fangyinfff** [comment]
Hi,

If you're looking to perform tasks related to proteins, you should currently use llama instead of llama2 for protein-related tasks. For your reference, the weights for llama can be found here: https://huggingface.co/baffo32/decapoda-research-llama-7B-hf.

**Comment by chengfengke** [comment]
> Hi,
> 
> If you're looking to perform tasks related to proteins, you should currently use llama instead of llama2 for protein-related tasks. For your reference, the weights for llama can be found here: https://huggingface.co/baffo32/decapoda-research-llama-7B-hf.

actually，I am going to run molecule model，
<img width="519" alt="image" src="https://github.com/zjunlp/Mol-Instructions/assets/56249816/5b6b339f-dc2b-4031-996b-da2aa9b7a160">
so I think that the problem might from llama2？

**Comment by chengfengke** [comment]
<img width="1085" alt="image" src="https://github.com/zjunlp/Mol-Instructions/assets/56249816/063dfe32-6465-4081-8a29-78c5b3ab03d5">
have you meet problem like this？

**Comment by Fangyinfff** [comment]
Did you download the model following the process we provided? I noticed that the model you downloaded is incorrect; we are using Llama-2-7b-chat.

**Comment by chengfengke** [comment]
ok，I will try it

**Comment by chengfengke** [comment]
I still can not execute it，is this model ok？https://www.modelscope.cn/models/shakechen/Llama-2-7b-chat/files，or I must load the model from huggingface？

**Comment by Fangyinfff** [comment]
We haven't tried downloading models from modelscope; we always download from Hugging Face.

**Comment by chengfengke** [comment]
ok，thank you

**Comment by chengfengke** [comment]
<img width="1374" alt="image" src="https://github.com/zjunlp/Mol-Instructions/assets/56249816/c68103ee-541a-4962-a636-c2b67b88e30f">
I notice that Llama-2-7b-chat on hf also don't have config.json
<img width="1133" alt="image" src="https://github.com/zjunlp/Mol-Instructions/assets/56249816/abbd92d8-b5a7-4c12-956b-d259bc944eda">

**Comment by chengfengke** [comment]
<img width="1321" alt="image" src="https://github.com/zjunlp/Mol-Instructions/assets/56249816/005363b0-c9b8-4112-b9c0-e9344d8fd58d">
do you guys use this model?

**Comment by Fangyinfff** [comment]
> <img alt="image" width="1321" src="https://private-user-images.githubusercontent.com/56249816/316294047-005363b0-c9b8-4112-b9c0-e9344d8fd58d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNjc5MjQsIm5iZiI6MTcxMTI2NzYyNCwicGF0aCI6Ii81NjI0OTgxNi8zMTYyOTQwNDctMDA1MzYzYjAtYzliOC00MTEyLWI5YzAtZTkzNDRkOGZkNThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDA4MDcwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwY2M3ZDkwY2U5NjFiNzViZDg5NjNiNWMxZDBlOTY1NGFlNzIxNThmNDFmNmRhNzU1ODFkZjRiZWE4ZmE5NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ueeildBs1oGRFgDm7don2H8yrc-rpsClBsHyyL1bKs4"> do you guys use this model?

It should be this one.

**Comment by zxlzr** [comment]
hi, do you have any other questions?

**Comment by chengfengke** [comment]
I run it successfully, thank you for those details and amazing work.
