### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by ricomnl** [zjunlp/Mol-Instructions#15]
hi there, your README mentions that the data set is not available for commerical use as per:
> The accompanying dataset is licensed under CC BY-NC-SA 4.0, which permits solely non-commercial usage.

but the license you quote in this repo and on huggingface does allow for commercial use. So my question is, did you mean to use another license or is this dataset indeed available for commercial use?

**Comment by Fangyinfff** [comment]
Hello,

Our dataset is licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/), and we have updated the README accordingly. You are welcome to use the dataset in compliance with this license.

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by ricomnl** [comment]
no, thanks a lot!
