### ISSUE TITLE
Question about protein design

### ISSUE THREAD

**Issue by zhuole1025** [zjunlp/Mol-Instructions#2]
Hi, I have read your work, which is really amazing! I notice that there are only protein understanding examples in the paper. So, I am wondering if you fine-tuned the LLaMA model with protein design tasks and if the fine-tuned model can perform generation. (Since I have tried and found it is challenging for LLM to generate samples from new modalities) Besides, I'd like to know how long does it take to fully fine-tune the whole LLaMA-7b on your dataset?
Really appreciated!

**Comment by Alexzhuan** [comment]
Hi,

I appreciate your interest in our work!

In Figure 5 (b, **protein design**), we present a case demonstrating the fine-tuned model's capacity for *de novo* protein design aligned with the user's design instruction. Specifically, by aligning the generated protein sequence to the UniProt database, we found that the generated protein exhibited significant sequence identity with the functional regions of a variety of proteins within the UniProt.

Indeed, cross-modality generation with LLM is a formidable challenge. Through instruction tuning on our Mol-Instructions, we found the models could gain an elementary level of comprehension for biomolecule "language". We believe that our curated instruction dataset could serve as a foundation to promote research in cross-modality (text-biomolecules) comprehension for LLM.

We performed the full fine-tuning using DeepSpeed ZeRO-2 on 6 A800 GPUs, and it took approximately 3 days to fine-tune the LLaMA-7b with our instruction dataset.

Feel free to ask if you have further questions.

**Comment by zhuole1025** [comment]
Thanks a lot! I see your results in Fig5, which are really impressive that LLM can learn and generate protein sequences. I have tried to add amino acids as additional tokens for LLM and perform instruction tuning. However, the results are relatively poor. (I guess its because the ability of LoRA is limited and full fine-tuning is needed)  
Looking forward to your future work~

**Comment by Alexzhuan** [comment]
Our preliminary investigation aligns with your findings; we observed that the utilization of LoRA for fine-tuning LLaMA didn't yield the expected results. Indeed, we concur with your assessment concerning the constraints of LoRA and the subsequent necessity for full fine-tuning.

Thank you for your feedback and interest in our work.
