### ISSUE TITLE
LORA Settings

### ISSUE THREAD

**Issue by lhallee** [zjunlp/Mol-Instructions#4]
Hello,

Are the LORA settings you used in the demo folder the same that were used for training?
Thanks!

**Comment by Fangyinfff** [comment]
Thank you for your interest in our work! 

The LORA settings in the demo folder were used for training molecular data. Detailed information about the hyperparameters used for training other datasets can be found in Table 6 of Appendix D in the [paper](https://arxiv.org/pdf/2306.08018.pdf).

**Comment by lhallee** [comment]
Do you guys have any public code for the ZeRO implementation for training the protein model? My lab has developed techniques to extend LLM vocabulary, so naturally, this is a really exciting avenue for this particular type of model. Unfortunately, I am personally unfamiliar with ZeRO. If you cannot share the code no worries, thanks for pointing me in the right direction! This is excellent work.

**Comment by Fangyinfff** [comment]
Hi,

while we currently do not have public code available for the ZeRO implementation, we do have plans to organize and release the code in the future. We appreciate your understanding in this matter.

You might find the following document helpful for your exploration: https://huggingface.co/docs/transformers/main_classes/deepspeed

**Comment by lhallee** [comment]
That is perfectly sensible. I appreciate the resources! All the best.
