### ISSUE TITLE
molT5 dataset

### ISSUE THREAD

**Issue by wawpaopao** [zjunlp/Mol-Instructions#7]
Why not use MolT5's fine-tuning dataset ？ This dataset contains additional descriptions of molecular structures.

**Comment by Fangyinfff** [comment]
Hi, 
In fact, our molecular data is homologous to molT5, both derived from PubChem.
This essentially means that our data encompasses the data from molT5.

**Comment by wawpaopao** [comment]
Hi,
They use CheBI instead of PubChem

**Comment by Fangyinfff** [comment]
Hi, 
The data for MolT5 comes from the [ChEBI annotations](https://pubchem.ncbi.nlm.nih.gov/source/ChEBI#data=Annotations) in [PubChem](https://pubchem.ncbi.nlm.nih.gov/source/ChEBI), and this data is already included in Mol-Instructions.

**Comment by wawpaopao** [comment]
yeah I see, but when processing data, some filtering methods may lead to a loss of information. In Pubchem, there are descriptions of molecular structures，like 'Trans-anol is a phenylpropanoid that is [phenol](https://pubchem.ncbi.nlm.nih.gov/compound/phenol) substituted at position 4 by a prop-1-enyl group (the trans-isomer) It is a phenylpropanoid and a member of [phenol](https://pubchem.ncbi.nlm.nih.gov/compound/phenol)s. It is functionally related to a phenol.' but in the instruction dataset , it is 'The molecule is a natural product found in Solidago odora and Osmorhiza aristata with data available' .   And why not use IUPAC name instead of SELFIES? IUPAC name contains a description of the structure.

**Comment by Fangyinfff** [comment]
The information you're referencing is described in the instructions as follows:
```
    {
        "instruction": "Synthesize a molecule that matches the given characteristics.",
        "input": "The molecule is a phenylpropanoid that is phenol substituted at position 4 by a prop-1-enyl group (the trans-isomer) It is a phenylpropanoid and a member of phenols. It is functionally related to a phenol.",
        "output": "[C][/C][=C][/C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][O]",
        "metadata": {
            "task": "description-guided molecule design"
        }
    },
 ```
Our approach follows the methodology employed by MolT5:
<img width="300" alt="image" src="https://github.com/zjunlp/Mol-Instructions/assets/61076726/03162dc5-bbb0-4a5a-b3f3-a2494392b995">
We opted for SELFIES because this descriptor is more conducive to model learning and facilitates the generation of valid molecules. Of course, the IUPAC name you mentioned can also be considered as a direction for future attempts. Thank you for your suggestion!

**Comment by wawpaopao** [comment]
yeah, but in the description_guided_moolecule_design.json, line2374976 ,it is '  {
        "instruction": "Based on the given information, design a molecule that meets the desired specifications.",
        "input": "The molecule is a natural product found in Solidago odora and Osmorhiza aristata with data available.",
        "output": "[C][/C][=C][/C][=C][C][=C][Branch1][Branch1][C][=C][Ring1][=Branch1][O]",
        "metadata": {
            "task": "description-guided molecule design",
            "split": "train"
        }
    },'

**Comment by Fangyinfff** [comment]
This is because our data comes not only from ChEBI annotations but also from other data sources within PubChem.

**Comment by wawpaopao** [comment]
I see! Thanks!

**Comment by Fangyinfff** [comment]
You're welcome! Feel free to discuss and exchange ideas.
